### ISSUE TITLE
Some functions broken with "-ffast-math" enabled

### ISSUE THREAD

**Issue by RafaGago** [xtensor-stack/xsimd#515] opened 2021-07-28 10:18 UTC
Tested both with vanilla Ubuntu 20.04 gcc and clang versions:

> gcc version 9.3.0 (Ubuntu 9.3.0-17ubuntu1~20.04) 
> clang version 10.0.0-4ubuntu1 

On commit: 

> 6288fb2 Merge pull request #506 from astrohawk/feature/bitwise-cast-complete

I noticed the error on tanh and exp. It might happen on more functions.

Test case:

> cmake -DCMAKE_CXX_FLAGS_FASTMATH:STRING="-DNDEBUG=1 -O2 -ffast-math -msse2" -DCMAKE_BUILD_TYPE=FASTMATH -DBUILD_TESTS=On -DDOWNLOAD_GTEST=On -Bbuild
> cmake --build build
> build/test/test_xsimd

This gives a list of failed SSE cases. I didn't look in depth.

Simpler test case:

> // file: main.cpp
> #include <stdio.h>
> #include <stdlib.h>
> #include <string.h>
> #include <xsimd/xsimd.hpp>
> 
> template <class T, unsigned long N>
> static auto get_exp (xsimd::batch<T, N> x)
> {
>   return xsimd::exp (x);
> }
> 
> static double getv()
> {
>   auto x = rand();
>   return ((double) x) / ((double) RAND_MAX) * ((x & 1) ? 1. : -1.);
> }
> 
> int main (int argc, char const* argv[])
> {
>   while (true) {
>     xsimd::batch<double, 2> x {getv(), getv()};
>     auto r = get_exp (x);
>     printf ("x: %f, exp: %f\n", x[0], r[0]);
>   }
>   return 0;
> };

Built like:
> /usr/bin/g++ -I <somewhere>/xsimd/include/ -O2 -msse2 -ffast-math main.cpp -o test

Outputs:

> x: -0.500448, exp: 1.000000
> x: -0.378448, exp: 1.000000
> x: 0.883919, exp: 2.000000
> x: 0.602014, exp: 1.000000
> x: -0.183409, exp: 1.000000
> x: -0.354358, exp: 1.000000
> x: -0.375457, exp: 1.000000
> x: -0.581081, exp: 1.000000
> x: 0.209094, exp: 1.000000
> x: -0.687917, exp: 1.000000
> x: 0.156919, exp: 1.000000
> x: 0.657123, exp: 1.000000
> x: 0.849249, exp: 2.000000
> x: -0.004719, exp: 1.000000
> x: -0.385270, exp: 1.000000
> x: 0.728181, exp: 2.000000
> x: 0.242487, exp: 1.000000
> x: -0.287589, exp: 1.000000
> x: 0.927757, exp: 2.000000
> x: -0.585650, exp: 1.000000
> x: -0.411578, exp: 1.000000
> x: 0.087031, exp: 1.000000

**Comment by RafaGago** [comment] 2021-07-28 10:42
I was trying what was going on on the previous program.

Compiled as -O0 works as expected:

/usr/bin/g++ -I /xsimd/include/ -O0 -g -msse2 -ffast-math main.cpp -o test

Changing to -Og makes it fail:

/usr/bin/g++ -I /xsimd/include/ -Og -g -msse2 -ffast-math main.cpp -o test

Removing "-fast-math" works with both versions. Weird.

**Comment by RafaGago** [comment] 2021-07-28 10:53
Unfortunately at -Og it's very hard for me to debug, as it is inlining and I have no previous knowledge of what is going on with the implementations.

**Comment by RafaGago** [comment] 2021-07-28 11:12
Fortunately the program behaves the same with printf.

I added a printf on "detail::exp_kernel<B, Tag, double>::compute", on "include/xsimd/math/xsimd_exponential.hpp:72". I send "0.66" as input, this is what happens:

>$ ./testcase_ok
>a: 0.660000, x: -0.033147, hi: -0.033147, lo: 0.000000, k: 1.000000, c: -0.033330, c2: 0.967396, c3: 1.934792, c4: 1.934792

> $ ./testcase_broken 
> a: 0.660000, x: -0.000000, hi: 0.000000, lo: 0.000000, k: 0.952179, c: -0.000000, c2: 1.000000, c3: 1.000000, c4: 1.000000

It seems that the range reduction function is broken (?).

**Comment by JohanMabille** [comment] 2021-07-29 20:19
Thanks for this detailed report and your investigation on this. We are currently working on refactoring the library, so this issue may be fixed in the next release. In the meantime, we plan to maintain a 7.x branch for convenience so that client can take the time to migrate to the new version. 

I am a bit swamped with this refactoring, but when it's done and when I am back from holidays, I will investigate this issue to fix it before backporting the change to the 7.x branch.

**Comment by JohanMabille** [comment] 2021-07-30 15:14
I've tagged a 7.6.0 which contains all the PR that could be backported from master until the commit that triggered the issue. The package should be available on conda-forge within an hour.

**Comment by RafaGago** [comment] 2021-08-01 08:39
Thanks! As you I'm on holidays. I'll check back as soon as I can. Can this be closed then?

**Comment by RafaGago** [comment] 2021-08-20 18:47
Sorry for the delay. I'm using this on a hobby audio project, so it took a while for being able to test.

I tested both 7.6.0 and 4decfbdfae7bbd3c036fdf9538c82b657caeb178 and the issue persists. I had no time to debug, but  I wrapped xsimd and I can toggle between a fallback thin-wrapper implementation based on <math.h> and xsimd with a #define. The <math.h> version works. The xsimd version breaks on the same places than did before.

**Comment by RafaGago** [comment] 2021-08-20 18:52
Same behavior on current master (cba930b0e0b6706e380aae2faebea4eda2cd69ac)

**Comment by serge-sans-paille** [comment] 2021-08-28 20:47
Some extra info wrt. master

```#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <xsimd/xsimd.hpp>

template <class T, class A>
static auto get_exp (xsimd::batch<T, A> x)
{ return xsimd::exp(x); }

static double getv()
{
  auto x = rand();
  return ((double)x) / ((double)RAND_MAX) * ((x & 1) ? 1. : -1.);
}

int main (int argc, char const* argv[])
{
  while (true) {
    xsimd::batch<double> x{getv(), getv()};
    auto r = get_exp(x);
    printf("x: %f, exp: %f\n", x.get(0), r.get(0));
  }
  return 0;
};


```

returns the same behavior with this option subset:

```
g++ fast.cpp -I../include -msse2 -O2 -fassociative-math -fno-signed-zeros -fno-trapping-math && ./a.out | head
```

so at some point, associative math, signed zero or trapping math leads to the behavior we're observing.
Note that by design, `-ffast-math` can lead to incorrect code. So it's not a *bug* to have incorrect code here. I'll still have a deeper look.

**Closed** 2021-08-30 06:50 UTC
